baseURL: "https://www.pedromealha.dev/"
title: WeNeedThePoh
paginate: 5
theme: PaperMod
copyright: 

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-JH9D63PCFF

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: pedromealha.dev
  description: "My personal website"
  keywords: [Blog, Portfolio, Tech, Books]
  author: Pedro Mealha
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "pedromealha"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile mode
  profileMode:
    enabled: true
    title: pedromealha.dev
    subtitle: "Welcome to my space. Here you will find my toughts and passions. Enjoy it."
    # imageUrl: "<img location>"
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      # - name: Posts
      #   url: blog
      - name: Projects
        url: projects
      - name: Books
        url: books

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://git.io/weneedthepooh"
    - name: linkedin
      url: "https://www.linkedin.com/in/pedro-mealha/"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/88977927-pedro-mealha"
    - name: unsplash
      url: "https://unsplash.com/@pedromealha"

  analytics:
    google:
      SiteVerificationTag: "CnSqIBYGJglsj5ZcapFc_L3MmnYwfHdyBs9TrKZqmJo"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/WeNeedThePoh/personal-website/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: blog
    #   name: blog
    #   url: /blog/
    #   weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
    - identifier: books
      name: bookshelf
      url: /books/
      weight: 30
    - identifier: contacts
      name: contacts
      url: /contacts/
      weight: 40
